Adding advisories for apache spark
wolfi-dev/advisories pull request #1077
Opened 2024-02-02 20:50 UTC by mamccorm

Creating advisories for apache spark.

2024-02-03 00:15 UTC, pdeslaur commented on spark.yaml
> +          note: protobuf-java classes are not included in runtime jars, but its metadata is still listed in META-INF pom.xml and properties files
I'm not sure I agree with this - I have found the protobuf classes in the shaded jar

2024-02-03 00:30 UTC, luhring requested changes
(placing a hold until we sync next week!)

2024-02-05 20:58 UTC, mamccorm commented on spark.yaml
> +          note: protobuf-java classes are not included in runtime jars, but its metadata is still listed in META-INF pom.xml and properties files
Resolving as we paired up earlier and walked through some of the items, including this one :)

2024-02-05 21:42 UTC, luhring commented
Continuing this in #1112

2024-02-05 21:42 UTC, closed without merging