py3-pip nak advisory CVE-2018-20225
wolfi-dev/advisories pull request #5849
Opened 2024-06-17 20:40 UTC by pnasrat

Same reason as py3.12-pip and below this is a contested advisory

2024-06-17 20:40 UTC, pnasrat commented
Merge after https://github.com/wolfi-dev/os/pull/20318

2024-06-20 12:40 UTC, cpanato submitted a review, later dismissed
thanks

2024-06-20 12:41 UTC, cpanato commented
@pnasrat can you rebase and fix the conflict?

2024-06-20 14:23 UTC, pnasrat commented
@cpanato done can you re-review

2024-06-20 14:25 UTC, cpanato requested changes
a small comment

2024-06-20 14:25 UTC, cpanato commented on py3-pip.advisories.yaml
> +          note: This vulnerability is disputed, and the consensus in the security community is that this is intended behavior, not a security flaw.
should be added after the detection event

2024-06-20 14:42 UTC, pnasrat commented on py3-pip.advisories.yaml
> +          note: This vulnerability is disputed, and the consensus in the security community is that this is intended behavior, not a security flaw.
@cpanato done!

2024-06-20 15:12 UTC, merged