gitness :: fix: GHSA-mw99-9chc-xw7r
wolfi-dev/advisories pull request #720
Opened 2024-01-02 09:38 UTC by hectorj2f

This vulnerability needs upstream changes in one of the dependencies 'code.gitea.io' to support a latest version of 'github.com/go-git/go-git/v5' due to the following error:

```
 .cache/go/pkg/mod/code.gitea.io/gitea@v1.21.3/modules/git/repo_commitgraph_gogit.go:28:44: cannot use index (variable of type "github.com/go-git/go-git/v5/plumbing/format/commitgraph".Index) as v2.Index value in argument to cgobject.NewGraphCommitNodeIndex: "github.com/go-git/go-git/v5/plumbing/format/commitgraph".Index does not implement v2.Index (missing method Close)
 ```

2024-01-02 22:42 UTC, pdeslaur requested changes
I appears the vulnerability can be resolved in gitness 3.0.0_beta5. Our package is at 3.0.0_beta2 - could you try the upgrade?

2024-01-08 09:04 UTC, hectorj2f commented
@pdeslaur i bumped gitness to beta5 but it still has deps to gitea `v1.17.2`. It fails building when we bump gitea to the fixed version for this vulnerability.

```
ℹ️  aarch64   | Building Gitness Server
ℹ️  aarch64   | go build -o ./gitness ./cmd/gitness
⚠️  aarch64   | # github.com/harness/gitness/git/adapter
⚠️  aarch64   | git/adapter/blame.go:74:32: cannot use args (variable of type []string) as []"code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to gitea.NewCommand
⚠️  aarch64   | git/adapter/commit.go:112:45: cannot use args (variable of type []string) as []"code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to gitea.NewCommand
⚠️  aarch64   | git/adapter/commit.go:246:62: cannot use ref (variable of type string) as "code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to gitea.NewCommand
⚠️  aarch64   | git/adapter/commit.go:398:31: cannot use args (variable of type []string) as []"code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to gitea.NewCommand
⚠️  aarch64   | git/adapter/commit.go:470:51: cannot use args (variable of type []string) as []"code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to gitea.NewCommand
⚠️  aarch64   | git/adapter/config.go:41:66: cannot use key (variable of type string) as "code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to git.NewCommand(ctx, "config", "--local").AddArguments
⚠️  aarch64   | git/adapter/config.go:41:71: cannot use value (variable of type string) as "code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to git.NewCommand(ctx, "config", "--local").AddArguments
⚠️  aarch64   | git/adapter/diff.go:60:29: cannot use args (variable of type []string) as []"code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to git.NewCommand
⚠️  aarch64   | git/adapter/diff.go:93:29: cannot use args (variable of type []string) as []"code.gitea.io/gitea/modules/git/internal".CmdArg value in argument to git.NewCommand
```

2024-01-08 19:35 UTC, pdeslaur commented
Got it!  However, GHSA-mw99-9chc-xw7r is not reported on the latest package version for gitness. Did you mean the advisory to be for a different vulnerability?

2024-01-08 19:57 UTC, hectorj2f commented
Yes, it is a different CVE-ID. I got these results:

```
wolfictl scan packages/aarch64/gitness-3.0.0_beta5-r0.apk
🔎 Scanning "packages/aarch64/gitness-3.0.0_beta5-r0.apk"
└── 📄 /usr/bin/gitness
        📦 code.gitea.io/gitea v1.17.2 (go-module)
            Low CVE-2023-3515 GHSA-cf6v-9j57-v6r6 fixed in 1.19.4
        📦 github.com/blevesearch/bleve/v2 v2.3.2 (go-module)
            Medium CVE-2022-31022
```

2024-01-08 19:57 UTC, hectorj2f commented
I can bump it in any way if we want that.

2024-01-08 20:03 UTC, pdeslaur commented
I'm fine with creating an advisory for GHSA-cf6v-9j57-v6r6 and CVE-2022-31022, but this PR is about GHSA-mw99-9chc-xw7r!

2024-01-08 20:39 UTC, hectorj2f commented
I can close this PR and update gitness to a recent version, then open a PR here for these two.

2024-01-08 20:39 UTC, closed without merging

2024-01-08 20:59 UTC, pdeslaur commented
Sounds good! fwiw - it looks like gitness is at beta5: https://github.com/wolfi-dev/os/pull/10784/files