imagemagick: fixed CVE CVE-2023-5341
wolfi-dev/advisories pull request #732
Opened 2024-01-07 18:29 UTC by rawlingsj

patch released upstream https://github.com/ImageMagick/ImageMagick/commit/aa673b2e4defc7cad5bec16c4fc8324f71e531f1

2024-01-08 12:54 UTC, cpanato requested changes
can you rebase once https://github.com/wolfi-dev/advisories/pull/743 is merged?

2024-01-12 10:55 UTC, cpanato commented
ping :)

2024-01-17 09:35 UTC, rawlingsj commented
All done

2024-01-17 11:12 UTC, cpanato commented on imagemagick.advisories.yaml
> +          fixed-version: 7.1.1.25-r0
should be in the end

2024-01-18 16:50 UTC, cpanato commented on imagemagick.advisories.yaml
> +          fixed-version: 7.1.1.25-r0
i will rebase

2024-01-18 17:02 UTC, cpanato approved these changes

2024-01-18 17:04 UTC, merged