metric-collector-for-apache-cassandra
wolfi-dev/advisories pull request #840
Opened 2024-01-13 08:45 UTC by developer-guy

2024-01-13 21:25 UTC, luhring requested changes

2024-01-13 21:25 UTC, luhring commented on metric-collector-for-apache-cassandra.advisories.yaml
> +          note: Pending upstream fix, this fix will require some code change
This doesn't explain why we can't fix it ourselves. (Also, no need to say "pending upstream fix" in the note text if "pending-upstream-fix" is already the event type!)

2024-01-13 23:06 UTC, developer-guy commented on metric-collector-for-apache-cassandra.advisories.yaml
> +          note: Pending upstream fix, this fix will require some code change
I was searching for the same CVE within the previous CVE entries, I used that one because the similar issue, sorry about that. I can give more detail about why the build fails due to upgrade.

2024-01-14 15:50 UTC, luhring submitted a review, later dismissed

2024-01-14 15:50 UTC, luhring commented on metric-collector-for-apache-cassandra.advisories.yaml
> +            To fix the CVE, we have to upgrade 'snakeyaml' to '2.0' or later but this fix will require some code change since the upgrade cause to build fail due to compilation errors like: "/src/mai
This is awesome, thanks @developer-guy!

LGTM, you'll just need to rebase I think

2024-01-14 17:28 UTC, luhring approved these changes

2024-01-14 17:30 UTC, merged